# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleauthuser',
            name='access_token',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='googleauthuser',
            name='refresh_token',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='googleauthuser',
            name='token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
