# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0002_auto_20170904_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauthuser',
            name='app_token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=254, unique=True),
        ),
    ]
